In [5]:
import torch

In [16]:
def sparse_dense_mul(s, d):
  i = s._indices()
  v = s._values()
  dv = d[i[0,:]]  # get values from relevant entries of dense matrix
  return torch.sparse.FloatTensor(i, v * dv, s.size())

In [30]:
#onehot = torch.sparse_coo_tensor(size=(5,10))
nonsparse_onehot = torch.arange(0, 5 * 10).reshape((5, 10))
onehot = nonsparse_onehot.to_sparse()
alpha = torch.arange(5)

In [31]:
print(onehot.shape, nonsparse_onehot.shape, alpha.shape)

torch.Size([5, 10]) torch.Size([5, 10]) torch.Size([5])


In [28]:
(nonsparse_onehot.T * alpha).T

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [33]:
res = sparse_dense_mul(onehot, alpha)
res.to_dense()

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [25]:
onehot.to_dense()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])