In [1]:
from utils import training, data
from utils.one_hot_graph import OneHotConv, OneHotGraph
from utils.baselines import OneHotGraph_Baseline
import torch
from torch.utils.tensorboard import SummaryWriter
from main import main


In [2]:
input_channels = 5
x_size = 10

In [1]:
import utils.data as data

In [3]:
dm = data.DataModule(data_name=  "tox21_original", split_mode="predefined")

## Finding out the maximum number of nodes and edges in 1 graph

In [26]:
import torch
select = torch.arange(0, 256)
lens = torch.tensor([2,5,3,6])
select[:lens]

TypeError: only integer tensors of a single element can be converted to an index

In [22]:
max_ = 0
for i in dm.make_test_loader():
    max_ = max((max(i[1]).detach().numpy(), max_))
for i in dm.make_val_loader():
    max_ = max((max(i[1]).detach().numpy(), max_))
for i in dm.make_train_loader():
    max_ = max((max(i[1]).detach().numpy(), max_))
print(max_)

max_ = 0
for i in dm.make_test_loader():
    max_ = max((*[a.shape[1] for a in i[2]], max_))
for i in dm.make_val_loader():
    max_ = max((*[a.shape[1] for a in i[2]], max_))
for i in dm.make_train_loader():
    max_ = max((*[a.shape[1] for a in i[2]], max_))
print(max_)

132
290


In [3]:
main(
    "iohgtry",
    configs=5,
    architecture="sinkhorn",
    device = "cuda",
    epochs=50,
    yaml_file="grids/grid_new_sinkhorn.yml"
)

Total number of Grid-Search configurations: 6912
Number of configurations now being trained 5
--------------------------------------------------------------------------------------------

Training config _hiddenchannels-64_headdepth-4_basedepth-5_basedropout-0.5_headdropout-0.2_lr-0.01_weightdecay-1e-08_batchsize-64_heads-8_donsinkhorniters-10 ... 

RuntimeError: The size of tensor a (8) must match the size of tensor b (1207) at non-singleton dimension 2

In [1]:
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler

In [18]:
import torch

In [15]:
def bla():
    a = torch.randn(10) * 1e7
    torch.log(a)

In [20]:
def bli(base = torch.tensor(6)):
    a = torch.randn(10) * 1e7
    torch.log(a) / torch.log(base)

In [22]:
torch.e

AttributeError: module 'torch' has no attribute 'e'

In [30]:
(torch.randint(0, 2, (100,)) != 0) + 1

tensor([1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1,
        1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1,
        2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1,
        2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1,
        1, 2, 2, 2])

In [1]:
from skopt import Optimizer

In [2]:
hyperparameter_optimizer = Optimizer([(1.0,10.0), ["bla", "blub"]])

In [3]:
for i in range(100):
    a = hyperparameter_optimizer.ask()
    if a[1] == "bla":
        hyperparameter_optimizer.tell(a, 5**a[0])
    if a[1] == "blub":
        hyperparameter_optimizer.tell(a, ((5**a[0])+100)**2)
    hyperparameter_optimizer.update_next()
    print(a)


[8.938669555503164, 'blub']
[9.995151906443214, 'bla']
[4.5471388847524095, 'bla']
[8.191960849085364, 'blub']
[8.927479338251695, 'blub']
[6.074917667031658, 'bla']
[2.4922746808408003, 'blub']
[5.3874647690386395, 'bla']
[3.446920492891699, 'bla']
[9.774033205378892, 'blub']
[1.0, 'bla']
[8.460590155607754, 'bla']
[1.2977707661125877, 'bla']
[1.2600573254595382, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']
[1.0003871974274217, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


/home/alexander/miniconda3/envs/ohg/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


[1.0, 'bla']


KeyboardInterrupt: 

# Onehot ADJ prod testing around

In [1]:
import torch

In [22]:
adj = torch.tensor([[0,1,0,0],[1,0,1,1],[0,1,0,1],[0, 1, 1, 0]], dtype=torch.float)
onehot = torch.eye(4, dtype=torch.float)
adj

tensor([[0., 1., 0., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.],
        [0., 1., 1., 0.]])

In [19]:
onehot = (onehot + onehot @ adj) + (onehot + onehot @ adj) @ adj

tensor([[2., 2., 1., 1.],
        [2., 4., 3., 3.],
        [1., 3., 3., 3.],
        [1., 3., 3., 3.]])

In [23]:
onehot + 2 * onehot @ adj + onehot @ adj @ adj

tensor([[2., 2., 1., 1.],
        [2., 4., 3., 3.],
        [1., 3., 3., 3.],
        [1., 3., 3., 3.]])